version: '3.8'
networks:
  main:
services:

  pg:
    image: postgres
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5438:5432"
    networks:
      main:
  redis:
    image: redis:alpine
    container_name: redis_clothing_store
    hostname: redis
    ports:
      - ${FASTAPI__REDIS__PORTS}
    networks:
      - main